language: python

python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r test-requirements.txt
  - python setup.py install
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below